Review Post and Tile PR
snardella/ParkReviewProject pull request #6
Opened 2021-01-29 16:04 UTC by snardella

- Created a getReviews fetch function to pull all the reviews on to the Park Show Page
- Added getReviews to useEffect so that existing reviews load upon initial page render
- Added getReviews as props so that new posted review triggers getReviews fetch request
- Added a Review Tile that would be mapped on the Park Show page.  This review tile presented username, rating and comment
- Made changes to reviewsRouter that now fetches reviews associated with the park and users associated with the reviews

2021-01-29 19:41 UTC, safang99 requested changes
Looks like there was some duplication and naming issues that would cause features to break.  After updating your associations always be sure to test them out in the console to uncover these bugs before moving on

2021-01-29 19:41 UTC, safang99 commented on client/src/components/NewReviewForm.js
> +        console.log("posted successfully", body)
we can remove the console.log statement now that it's working

2021-01-29 19:41 UTC, safang99 commented on client/src/components/ReviewForm.js
> +// This post request should live in the park show page.
We can remove one of the empty lines and commented out code here.  We only need to keep one empty line between functions for readability

2021-01-29 19:41 UTC, safang99 commented on client/src/components/NewReviewForm.js
> +const NewReviewForm = (props) => {
This is your `NewReviewForm` component but it also seems that there is a `ReviewForm` component?

2021-01-29 19:41 UTC, safang99 commented on client/src/components/ReviewForm.js
> +const NewReviewForm = ({ postTask }) => {
This is a second Review form in `ReviewForm.js`?  I'm guessing only one of these is supposed to exist for adding reviews

2021-01-29 19:41 UTC, safang99 commented on client/src/components/ReviewForm.js
> +      const response = await fetch(`/api/v1/parks/${parkId}/reviews`, {
`parkId` is not defined

2021-01-29 19:41 UTC, safang99 commented on client/src/components/layout/ParkShow.js
> +  const getReviews = async () => {
After updating the API endpoint this `getReviews` can be removed

2021-01-29 19:41 UTC, safang99 commented on client/src/components/layout/ParkShow.js
> +    getReviews()
This should instead be handled through a serializer, so that when we fetch a `park` it returns with its associated `reviews`.

2021-01-29 19:41 UTC, safang99 commented on client/src/components/NewReviewForm.js
> +        props.getReviews()
If the goal is to have this function affect the state in `ParkShow` upon a successful submission than that is where this function should live and we can pass it down through props to the `NewReviewForm`

2021-01-29 19:41 UTC, safang99 commented on client/src/components/layout/ParkShow.js
> +        getReviews={getReviews}
We can instead pass the POST fetch function once we move it here

2021-01-29 19:41 UTC, safang99 commented on server/src/models/Review.js
> +    return {
add a line between 10&11

2021-01-29 19:41 UTC, safang99 commented on server/src/models/Review.js
> +          to: "park.id",
This should be plural `parks`

2021-01-29 19:41 UTC, safang99 commented on server/src/models/Park.js
> +          to: "user.id",
This needs to be plural `users`

2021-01-29 19:41 UTC, safang99 commented on server/src/models/User.js
> +    return {
add a line between 40 & 41

2021-01-29 19:41 UTC, safang99 commented on server/src/models/User.js
> +          to: "reviews.usersId",
This should be singular `userId` to match the column on the reviews table

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/parkReviewsRouter.js
> +const { ValidationError } = objection;
We can reorganize these lines to something like

```js
import express from "express";
import objection from "objection";
const { ValidationError } = objection;

import { Review } from "../../../models/index.js";
import cleanUserInput from "../../../services/cleanUserInput.js";
```

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/parkReviewsRouter.js
> +    console.log(parkId);
Stray console.log

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/parkReviewsRouter.js
> +        console.log(newReview);
remove the console.log

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/parkReviewsRouter.js
> +
Looks like the indentation is set to 4 in this file.  Make sure everyone has their tab space setting on 2 and re save this file

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/parksRouter.js
> +const { ValidationError } = objection;
Again we can clean up the import statements by grouping together what exists in modules that we installed and what is coming from files that we wrote

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/parksRouter.js
> +
remove 55-56

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/parksRouter.js
> +    const park = await Park.query().findById(parkId);
Here is where we can use a `$relatedQuery("reviews")`

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/api/v1/reviewsRouter.js
> +});
After making use of our relatedQuery method we can remove this router

2021-01-29 19:41 UTC, safang99 commented on server/src/routes/rootRouter.js
> +
We don't need to separate these with a space yet

2021-02-01 21:03 UTC, dovakeen118 requested changes
Need to add some serializers and check your associations!

2021-02-01 21:03 UTC, dovakeen118 commented on client/src/components/NewParkForm.js
> +import { Redirect } from "react-router-dom";
We can group these together based on what we're importing from libraries vs importing from our own files
```
import React, { useState } from "react";
import { Redirect } from "react-router-dom";

import translateServerErrors from "../services/translateServerErrors.js";
import FormError from "./layout/FormError.js";
```

2021-02-01 21:03 UTC, dovakeen118 commented on client/src/components/layout/ParkShow.js
> +        getPark()
We shouldn't need to run the _entire_ fetch request again to grab the park and its reviews because we just executed a Post request to the back end and the router should be sending back the new review for this park, in which case we can just update that piece of state with the new data
```
setPark({
  ...park,
  reviews: [ ...reviews, body.park ]
})
```

You would want to check what your router is sending for what you'll have access to in `body`

2021-02-01 21:03 UTC, dovakeen118 commented on client/src/components/layout/ParkShow.js
> +      />
You might consider placing your form on the page before any reviews. If you think about the state of your app once there are 50+ reviews for a park, a user probably won't know that waaaaaay at the bottom is a form where they can also submit a review

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/db/migrations/20210127101731_createParks.cjs
> +    table.string("picture", 1000000);
Is there a reason you added a length property to your picture column?

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/db/seeders/ParkSeeder.js
> +        userId: "1",
To make this seed data stronger we can query for an existing user in your database and attach their `user.id` to this property instead of hardcoding a value of "1"

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/models/Park.js
> +      users: {
A Park belongs to one User, so this association should be singular `user`

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/models/User.js
> +        relation: Model.ManyToManyRelation,
What is your join table/ association between users and parks?

A Park belongs to a User
A User has many Parks

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/models/User.js
> +    const Review = require("./Review.js")
For consistency I would update these model import statements to match your imports in your Router, importing from `index`

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/models/Review.js
> +    const User = require("./User.js");
For consistency I would update these model import statements to match your imports in your Router, importing from `index`

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/models/Park.js
> +    const User = require("./User.js");
For consistency I would update these model import statements to match your imports in your Router, importing from `index`

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/routes/api/v1/parksRouter.js
> +import Park from "../../../models/Park.js";
Choose one method for importing models so it is consistent throughout your app

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/routes/serializer/ParkSerializer.js
> +        debugger
remove debuggers!

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/routes/serializer/ParkSerializer.js
> +        })
Take a look at this staff announcement for how you can clean up this nested async serializer
https://launchboston31.slack.com/archives/C01C527MGMR/p1611955552068400

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/routes/api/v1/parksRouter.js
> +    const newPark = await Park.query().insertAndFetch(formInput);
This new park should be passed through the serializer to remove things like the timestamps

2021-02-01 21:03 UTC, dovakeen118 commented on server/src/routes/serializer/ParkSerializer.js
> +            serializedPark.reviews[i].user = await serializedPark.reviews[i].$relatedQuery("user")
We will need a ReviewSerializer! And probably a UserSerializer if you're also trying to find the User who made the review

2021-02-01 21:08 UTC, Magowntown commented on server/src/db/migrations/20210127101731_createParks.cjs
> +    table.string("picture", 1000000);
in case a URL is submitted for the picture that exceeds the 250+ word limit. URLs can get crazy long.

2021-02-02 18:35 UTC, nwalberts commented on client/src/components/NewParkForm.js
> +        console.log("posted successfully", body);
remove console.log

2021-02-02 18:35 UTC, nwalberts commented on client/src/components/layout/ParkShow.js
> +        getPark();
nooooooooo and the code was so nice! Why are we getting the park again? that info hasnt changed. remove line 57 and this should work the same, unless there is someting I am missing?

2021-02-02 18:35 UTC, nwalberts commented on server/src/models/Park.js
> +      users: {
this should be singular: "user" for the name of the relationMapping

2021-02-02 18:35 UTC, nwalberts commented on server/src/routes/api/v1/parksRouter.js
> +    return res.status(201).json({ park: newPark });
has Kerrin's comment been addressed?

2021-02-02 20:15 UTC, merged